In [1]:
import pandas as pd
import numpy as np

In [2]:
xls = pd.ExcelFile('Dataset/Training Set (1).xlsx')
df1 = pd.read_excel(xls, 'training_1')
df2 = pd.read_excel(xls, 'training_2')
master=pd.ExcelFile('Dataset/master dataset.xlsx')
master=pd.read_excel(master, 'master_sheet')

In [3]:
master.head()

make    model     variant fuel_type    cc  seating_capacity  \
0  ALFA ROMEO  156 GTA         STD    Petrol  3179                 5   
1  ALFA ROMEO  VINTAGE       ROMEO    Petrol  1100                 5   
2  ALFA ROMEO  VINTAGE  ALFA ROMEO    Petrol  1750                 5   
3  ALFA ROMEO  VINTAGE  ALFA ROMEO    Petrol  1570                 5   
4  ALFA ROMEO  VINTAGE  ALFA ROMEO    Petrol  1110                 5   

       output  
0  1110110101  
1  1110110201  
2  1110110202  
3  1110110203  
4  1110110204

In [4]:
df1.head()

make      model                       variant    cc  \
0        HONDA       CR-V                        2.4 MT  2354   
1        HONDA       CR-V                        2.4 MT  2354   
2   VOLKSWAGEN       AMEO  1.5L TDI MT COMFORTLINE PLUS  1498   
3         FORD       FIGO    1.2 TITANIUM SPORTS PETROL  1196   
4  LAMBORGHINI  AVENTADOR                    S LP 740-4  6498   

   seating_capacity fuel_type  local_output  
0                 5    PETROL         12623  
1                 5    PETROL         12623  
2                 5    DIESEL         36811  
3                 5    PETROL         36819  
4                 2    PETROL         37548

In [5]:
df2.head()

make    model         variant    cc  seating_capacity fuel_type  \
0  HYUNDAI  SANTRO         SANTRO L  1086                 5  Petrol C   
1  HYUNDAI  ACCENT       ACCENT GVS  1495                 5  Petrol C   
2  HYUNDAI  ACCENT       ACCENT GLX  1495                 5  Petrol C   
3  HYUNDAI  ACCENT      ACCENT VIVA  1599                 5  Petrol C   
4  HYUNDAI  ACCENT   ACCENT TORNADO  1599                 5  Petrol C   

   local_code  
0         109  
1         122  
2         124  
3         125  
4         126

In [6]:
master.columns

Index(['make', 'model', 'variant', 'fuel_type', 'cc', 'seating_capacity',
       'output'],
      dtype='object')

In [7]:
df1.columns

Index(['make', 'model', 'variant', 'cc', 'seating_capacity', 'fuel_type',
       'local_output'],
      dtype='object')

In [8]:
df2.columns

Index(['make', 'model', 'variant', 'cc', 'seating_capacity', 'fuel_type',
       'local_code'],
      dtype='object')

In [9]:
master['fuel_type'].unique()

array(['Petrol', 'Diesel', 'Electric', 'CNG', 'LPG'], dtype=object)

In [10]:
df1['fuel_type'].unique()

array(['PETROL', 'DIESEL', 'CNG', 'LPG', 'ELECTRIC', 'Diesel'],
      dtype=object)

In [11]:
df2['fuel_type'].unique()

array(['Petrol C', 'Diesel C', 'Petrol P', 'Diesel P', 'Electric C'],
      dtype=object)

In [12]:
master['seating_capacity'].unique()

array([ 5,  4,  2,  7,  6,  8, 10,  9, 12, 13, 14,  1])

In [13]:
df1['seating_capacity'].unique()

array([ 5,  2,  8,  7,  9,  4, 10,  6, 11, 14, 13, 12, 22, 16, 18, 15])

In [14]:
df2['seating_capacity'].unique()

array([ 5,  8,  7,  2, 10,  6,  4, 12,  9, 14, 25,  3, 21, 11,  0])

In [15]:
df2[df2['seating_capacity']==21]

make model   variant    cc  seating_capacity fuel_type  \
703  MERCEDES BENZ   RF   RF 1830.  4598                21  Diesel P   

     local_code  
703       15964

In [16]:
df2[df2['seating_capacity']==0]

make   model                            variant    cc  \
2921        AUDI     Q7             Q7 45 TFSI PREMIUM PLUS  1984   
2929      TOYOTA  HIACE                 HIACE COMMUTER 8STR  2982   
3076      TOYOTA  HIACE                            HIACE GL  2754   
3179  LAND ROVER  RANGE   RANGE ROVER VELAR 2.0 R DYNAMIC S  1999   

      seating_capacity fuel_type  local_code  
2921                 0  Petrol P       26089  
2929                 0  Diesel P       26131  
3076                 0  Diesel P       26861  
3179                 0  Diesel P       27475

In [17]:
_make = "AUDI"
_model = "Q7"
_fuel = "Petrol"

In [18]:
int(master[(master['make']==_make) & (master['model']==_model) & (master['fuel_type']==_fuel)]['seating_capacity'].mean())

6

In [19]:
list(filter(lambda x:x.islower(),list(master['variant'].unique())))

['316i',
 '318i',
 '320d',
 '320i',
 '325i',
 '330i',
 '520i',
 '523i',
 '525d 2.0',
 '525i',
 '528i',
 '530d',
 '530i',
 '535i',
 '540i',
 '640d',
 '650i',
 '650i 4.4',
 '728i',
 '3.0d 1',
 '3.0d 2',
 '35i',
 'tour',
 '250d',
 '350d',
 'tourin']

In [20]:
df = pd.read_csv("df.csv")

In [21]:
df = df[df['make'].notna()]

In [22]:
# import statistics as st
# for i in df.index:
#     if type(df['variant-'][i])!=type("STRING"):
#         l = list(df[(df['make']==df.make[i]) & (df['model']==df.model[i])]["variant"])
#         if len(l)>0:
#                 df['variant'][i] = st.mode(l)
#         else:
#                 df['variant'][i] = ""

In [23]:
df.columns

Index(['Unnamed: 0', 'make', 'model', 'variant', 'cc', 'seating_capacity',
       'fuel_type', 'local_code'],
      dtype='object')

In [24]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [25]:
df

make       model                       variant    cc  \
0             HONDA  VANTAGE V8                        2.4 MT  2354   
1        VOLKSWAGEN        AMEO  1.5L TDI MT COMFORTLINE PLUS  1498   
2              FORD        FIGO    1.2 TITANIUM SPORTS PETROL  1196   
3       LAMBORGHINI   AVENTADOR                    S LP 740-4  6498   
4             SKODA       RAPID        MONTE CARLO 1.6 MPI AT  1598   
...             ...         ...                           ...   ...   
9073           JEEP     COMPASS   COMPASS LONGITUDE OPTION AT  1368   
9074  NISSAN MOTORS     MAGNITE      MAGNITE 1.0 XV EXECUTIVE   999   
9075          SKODA     KODIAQ        KODIAQ 2.0 TSI STYLE AT  1984   
9076          SKODA     KODIAQ   KODIAQ 2.0 TSI SPORT LINE AT  1984   
9077          SKODA     KODIAQ      KODIAQ 2.0 TSI L AND K AT  1984   

      seating_capacity fuel_type  local_code  
0                    5    Petrol       12623  
1                    5    Diesel       36811  
2                    5    Petrol       36819  
3                    2    Petrol       37548  
4                    5    Petrol       37128  
...                ...       ...         ...  
9073                 5    Petrol       29012  
9074                 5    Petrol       29018  
9075                 7    Petrol       29038  
9076                 7    Petrol       29041  
9077                 7    Petrol       29042  

[9074 rows x 7 columns]

In [26]:
len(df['make'].unique())

77

In [27]:
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()
for i in df.columns[:-1]:
    print(i)
    df[i] = ord_enc.fit_transform(df[[i]])
df.dropna(inplace=True)

make
model
variant
cc
seating_capacity
fuel_type


In [36]:
# Run this program on your local python
# interpreter, provided you have installed
# the required libraries.

# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Function importing Dataset
def importdata():
	balance_data = df
	
	# Printing the dataswet shape
	print ("Dataset Length: ", len(balance_data))
	print ("Dataset Shape: ", balance_data.shape)
	
	# Printing the dataset obseravtions
	print ("Dataset: ",balance_data.head())
	return balance_data

# Function to split the dataset
def splitdataset(balance_data):

    # Separating the target variable
    X = balance_data.values[:, 0:6]
    Y = balance_data.values[:, -1]

    # Splitting the dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size = 0.3, random_state = 100)
    print("X_train:",X_train,"Y_Train:",y_train)

    return X, Y, X_train, X_test, y_train, y_test
	
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):

	# Creating the classifier object
	clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

	# Performing training
	clf_gini.fit(X_train, y_train)
	return clf_gini
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):

	# Decision tree with entropy
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 3, min_samples_leaf = 5)

	# Performing training
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


# Function to make predictions
def prediction(X_test, clf_object):

	# Predicton on test with giniIndex
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	print(y_pred)
	return y_pred
	
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: ",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred))

# Driver code
def main():
	
	# Building Phase
	data = importdata()
	X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
	clf_gini = train_using_gini(X_train, X_test, y_train)
	clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
	
	# Operational Phase
	print("Results Using Gini Index:")
	
	# Prediction using gini
	y_pred_gini = prediction(X_test, clf_gini)
	cal_accuracy(y_test, y_pred_gini)
	
	print("Results Using Entropy:")
	# Prediction using entropy
	y_pred_entropy = prediction(X_test, clf_entropy)
	cal_accuracy(y_test, y_pred_entropy)
	
	
# Calling main function
if __name__=="__main__":
	main()


Dataset Length:  8999
Dataset Shape:  (8999, 7)
Dataset:     make  model  variant     cc  seating_capacity  fuel_type  local_code
0  27.0  492.0   1195.0  183.0               3.0        4.0       12623
1  74.0   51.0    744.0  106.0               3.0        1.0       36811
2  23.0  179.0    285.0   60.0               3.0        4.0       36819
3  36.0   62.0   6083.0  371.0               1.0        4.0       37548
4  64.0  396.0   5293.0  123.0               3.0        4.0       37128
X_train: [[2.900e+01 1.220e+02 5.390e+02 1.050e+02 3.000e+00 4.000e+00]
 [6.900e+01 4.150e+02 6.234e+03 1.440e+02 6.000e+00 1.000e+00]
 [6.900e+01 4.730e+02 6.987e+03 1.440e+02 4.000e+00 1.000e+00]
 ...
 [3.500e+01 4.240e+02 6.453e+03 1.020e+02 3.000e+00 1.000e+00]
 [2.900e+01 5.260e+02 7.598e+03 6.100e+01 3.000e+00 4.000e+00]
 [2.900e+01 3.900e+01 1.965e+03 1.030e+02 3.000e+00 4.000e+00]] Y_Train: [43105.   141. 17472. ... 23823. 19099.   122.]
Results Using Gini Index:
Predicted values:
[12739. 12585. 1

/home/gb/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/gb/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/gb/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/gb/.local/lib/python3.10/site-packages/sklearn/metr

In [ ]:
len(df['make'].unique())

In [ ]:
df.isna

In [50]:
out = pd.read_csv("output.csv")

In [51]:
out

map_code local_code
0  help,no    No,need
1  help,no    No,need

In [ ]:
lst = []
output = pd.DataFrame(lst, columns =['local_code', 'mapped_code'])
output.to_csv('ouput.csv')